export const AUTH_LOGIN_LOADING = 'AUTH_LOGIN_LOADING';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CLEAR_AUTH_MESSAGE = 'CLEAR_AUTH_MESSAGE';